(function () {
  'use strict';
  var shell = document.getElementById('shell'), face = document.getElementById('face'), mouth = document.getElementById('mouth');
  var status = document.getElementById('status'), message = document.getElementById('message'), form = document.getElementById('fallback'), input = document.getElementById('request');
  var pairing = document.getElementById('pairing'), modeButton = document.getElementById('mode-toggle'), controlsToggle = document.getElementById('controls-toggle');
  var settingsPanel = document.getElementById('settings'), settingsButton = document.getElementById('settings-toggle'), settingsClose = document.getElementById('settings-close'), micSource = document.getElementById('mic-source'), cameraSource = document.getElementById('camera-source'), interfaceSelect = document.getElementById('interface-select');
  var controls = document.getElementById('controls'), tabs = document.getElementById('tabs'), targetSelect = document.getElementById('light-target'), colorInput = document.getElementById('light-color'), colorSwatches = document.getElementById('color-swatches'), brightness = document.getElementById('brightness'), brightnessValue = document.getElementById('brightness-value'), effectGrid = document.getElementById('effect-grid'), toolName = document.getElementById('tool-name'), toolArguments = document.getElementById('tool-arguments'), resultText = document.getElementById('result-text');
  var tvProfile = document.getElementById('tv-profile'), tvTarget = document.getElementById('tv-target'), tvSpeed = document.getElementById('tv-speed');
  var scanLamps = document.getElementById('scan-lamps'), repairLamps = document.getElementById('repair-lamps'), pairedLamps = document.getElementById('paired-lamps'), lampScanResults = document.getElementById('lamp-scan-results');
  var token = sessionStorage.getItem('jarvisToken'), sessionId = null, speaking = false, mouthTimer = null, listenWanted = false, wakeOnly = false, processing = false, commandText = '', commandTimer, listenTimeout, recognition, restartTimer, audioContext, audioUnlocked = false;
  var clientLogLast = {};
  var musicSync = false, musicAudio, musicStream, musicSource, musicAnalyser, musicTimer, musicLastColor = '';
  var cameraSync = false, cameraTimer, cameraStream, cameraVideo, cameraCanvas, cameraContext, cameraLastColor = '', cameraFailures = 0, cameraTarget = null;
  var sphere = window.JarvisSphere && window.JarvisSphere.create(document.getElementById('jarvis-sphere'), { status: document.getElementById('sphere-status'), message: document.getElementById('sphere-message') });
  var interfaces = { sphere: true, classic: true };
  function isLocalClient() { return location.hostname === 'localhost' || location.hostname === '127.0.0.1' || location.hostname === '[::1]' || location.hostname === '::1'; }
  function markSurfaceCompat() { var ua = navigator.userAgent || ''; if (/(Windows NT 6\.[23]|Windows Phone|IEMobile|Trident|ARM;|Touch)/i.test(ua) && shell.className.indexOf('surface-compat') < 0) shell.className += ' surface-compat'; }
  function currentInterface() { var saved = getSetting('jarvisInterface', 'default'); if (saved === 'default' || !interfaces[saved]) return 'sphere'; return saved; }
  function setInterface(name, persist) { var resolved = name === 'default' || !interfaces[name] ? 'sphere' : name; shell.setAttribute('data-interface', resolved); if (interfaceSelect) interfaceSelect.value = name === 'classic' ? 'classic' : name === 'sphere' ? 'sphere' : 'default'; if (persist) saveSetting('jarvisInterface', name); if (sphere) { if (resolved === 'sphere') { sphere.start(); sphere.resize(); } else sphere.stop(); } }
  function setControlsVisible(visible) { if (!controls) return; controls.hidden = !visible; shell.setAttribute('data-controls', visible ? 'open' : 'closed'); if (controlsToggle) { controlsToggle.textContent = visible ? 'Hide' : 'Controls'; controlsToggle.setAttribute('aria-label', visible ? 'Hide controls' : 'Show controls'); controlsToggle.title = visible ? 'Hide controls' : 'Show controls'; } }
  function toggleControls() { setControlsVisible(!controls || controls.hidden); }
  function setState(state, data) { shell.className = shell.className.replace(/state-[a-z]+/, 'state-' + state); face.setAttribute('aria-label', 'Jarvis, ' + state); status.textContent = state === 'idle' ? 'JARVIS' : state.toUpperCase(); if (data && data.message) message.textContent = data.message; if (sphere) sphere.setState(state, data || {}); if (state !== 'speaking') stopSpeaking(); if (state === 'idle') mouth.className = 'mouth smile'; }
  function stopMouth() { speaking = false; if (mouthTimer) clearTimeout(mouthTimer); mouthTimer = null; }
  function stopSpeaking() { stopMouth(); if ('speechSynthesis' in window) { try { speechSynthesis.cancel(); } catch (ignore) {} } }
  function moveMouth() { if (!speaking) return; var states = ['closed', 'small', 'open', 'wide', 'small', 'smile', 'open']; mouth.className = 'mouth ' + states[Math.floor(Math.random() * states.length)]; mouthTimer = setTimeout(moveMouth, 85 + Math.random() * 190); }
  function clearListeningTimeout() { if (listenTimeout) clearTimeout(listenTimeout); listenTimeout = null; }
  function armListeningTimeout() { clearListeningTimeout(); listenTimeout = setTimeout(function () { if (!wakeOnly || processing) return; wakeOnly = false; commandText = ''; setState('idle', { message: 'Ready' }); startListening(); }, 6500); }
  function startListening() { if (!recognition || !listenWanted || speaking || processing) return; clearTimeout(restartTimer); recognition.continuous = !wakeOnly; recognition.interimResults = wakeOnly; try { recognition.start(); } catch (ignore) { restartTimer = setTimeout(startListening, 400); } }
  function unlockAudio() { var AudioContext = window.AudioContext || window.webkitAudioContext; audioUnlocked = true; try { if (AudioContext && !audioContext) audioContext = new AudioContext(); if (audioContext && audioContext.state === 'suspended') audioContext.resume(); if ('speechSynthesis' in window) speechSynthesis.resume(); } catch (ignore) {} }
  function playTone(from, to, length, volumeLevel) { var AudioContext = window.AudioContext || window.webkitAudioContext, audio; if (!AudioContext) return; try { audio = audioContext || new AudioContext(); audioContext = audio; function begin() { var tone = audio.createOscillator(), volume = audio.createGain(), now = audio.currentTime; tone.type = 'sine'; tone.frequency.setValueAtTime(from, now); tone.frequency.exponentialRampToValueAtTime(to, now + length * 0.7); volume.gain.setValueAtTime(0.0001, now); volume.gain.exponentialRampToValueAtTime(volumeLevel, now + 0.015); volume.gain.exponentialRampToValueAtTime(0.0001, now + length); tone.connect(volume); volume.connect(audio.destination); tone.start(now); tone.stop(now + length + 0.01); } if (audio.state === 'suspended') audio.resume().then(begin).catch(function () {}); else begin(); } catch (ignore) {} }
  function playWakeChime() { playTone(880, 1320, 0.22, 0.12); }
  function playThinkingSound() { playTone(260, 390, 0.32, 0.07); }
  function preferredVoice() { var voices, i, voice, name; if (!('speechSynthesis' in window)) return null; voices = speechSynthesis.getVoices ? speechSynthesis.getVoices() : []; for (i = 0; i < voices.length; i += 1) { voice = voices[i]; name = (voice.name || '').toLowerCase(); if (/^en[-_]gb/i.test(voice.lang || '') && /(daniel|george|ryan|arthur|thomas|male)/.test(name)) return voice; } for (i = 0; i < voices.length; i += 1) { voice = voices[i]; if (/^en[-_]gb/i.test(voice.lang || '')) return voice; } return null; }
  function say(text, done, state) { var voice; if (!('speechSynthesis' in window)) { if (done) done(); else { setState('idle'); startListening(); } return; } unlockAudio(); if (recognition) { try { recognition.abort(); } catch (ignore) {} } setState(state || 'speaking'); speaking = true; if (!state || state === 'speaking') moveMouth(); var utterance = new SpeechSynthesisUtterance(text); voice = preferredVoice(); if (voice) { utterance.voice = voice; utterance.lang = voice.lang; } else utterance.lang = 'en-GB'; utterance.rate = 0.96; utterance.pitch = 0.88; utterance.onend = utterance.onerror = function () { stopMouth(); if (done) done(); else { setState('idle'); startListening(); } }; speechSynthesis.cancel(); speechSynthesis.speak(utterance); }
  function getSetting(name, fallback) { try { return localStorage.getItem(name) || fallback; } catch (ignore) { return fallback; } }
  function saveSetting(name, value) { try { localStorage.setItem(name, value); } catch (ignore) {} }
  function apiPost(url, body, ok, fail) { var xhr; if (window.fetch) { fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token }, body: JSON.stringify(body || {}) }).then(function (response) { if (!response.ok) return response.text().then(function (text) { var data = {}; try { data = JSON.parse(text); } catch (ignore) {} throw Error(data.detail || 'Connection issue.'); }); return response.json(); }).then(ok).catch(fail || function () {}); return; } xhr = new XMLHttpRequest(); xhr.open('POST', url, true); xhr.setRequestHeader('Content-Type', 'application/json'); xhr.setRequestHeader('Authorization', 'Bearer ' + token); xhr.onreadystatechange = function () { var data; if (xhr.readyState !== 4) return; if (xhr.status >= 200 && xhr.status < 300) { try { ok(JSON.parse(xhr.responseText)); } catch (ignore) { ok({}); } } else if (fail) { try { data = JSON.parse(xhr.responseText); } catch (ignore) { data = {}; } fail(Error(data.detail || 'Connection issue.')); } }; xhr.send(JSON.stringify(body || {})); }
  function apiGet(url, ok, fail) { var xhr; if (window.fetch) { fetch(url, { headers: { 'Authorization': 'Bearer ' + token } }).then(function (response) { if (!response.ok) return response.text().then(function (text) { var data = {}; try { data = JSON.parse(text); } catch (ignore) {} throw Error(data.detail || 'Connection issue.'); }); return response.json(); }).then(ok).catch(fail || function () {}); return; } xhr = new XMLHttpRequest(); xhr.open('GET', url, true); xhr.setRequestHeader('Authorization', 'Bearer ' + token); xhr.onreadystatechange = function () { var data; if (xhr.readyState !== 4) return; if (xhr.status >= 200 && xhr.status < 300) { try { ok(JSON.parse(xhr.responseText)); } catch (ignore) { ok({}); } } else if (fail) { try { data = JSON.parse(xhr.responseText); } catch (ignore) { data = {}; } fail(Error(data.detail || 'Connection issue.')); } }; xhr.send(); }
  function clientLog(event, data) { var key, now, minimumGap; if (!token || !window.fetch) return; data = data || {}; key = event + ':' + (data.error || data.final || ''); now = new Date().getTime(); minimumGap = event === 'speech_error' ? 15000 : event === 'speech_followup_result' && !data.final ? 1200 : 0; if (minimumGap && clientLogLast[key] && now - clientLogLast[key] < minimumGap) return; clientLogLast[key] = now; try { fetch('/api/client/log', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token }, body: JSON.stringify({ event: event, data: data }) }).catch(function () {}); } catch (ignore) {} }
  function showOutcome(text, isError) { if (resultText) resultText.textContent = text || 'Done.'; message.textContent = text || 'Done.'; if (isError) setState('error', { message: text || 'Connection issue.' }); }
  function targetArgs(extra) { var args = extra || {}; if (targetSelect && targetSelect.value) args.target = targetSelect.value; return args; }
  function callTool(name, args, done) { var color; if (!token) return; color = sphere && sphere.colorFromTool(name, args || {}); if (sphere) sphere.startAction('Running ' + name, color); showOutcome('Running ' + name + '...'); apiPost('/api/tools/call', { name: name, arguments: args || {} }, function (data) { showOutcome(data.content || 'Done.'); if (sphere) sphere.completeAction(color); if (done) done(data); }, function (error) { showOutcome(error.message || 'Tool failed.', true); if (sphere) sphere.failAction(error.message || 'Tool failed.'); }); }
  function hexToRgb(hex) { var value = (hex || '#ffffff').replace('#', ''); return { red: parseInt(value.substr(0, 2), 16), green: parseInt(value.substr(2, 2), 16), blue: parseInt(value.substr(4, 2), 16) }; }
  function rgbToHex(red, green, blue) { function part(value) { value = Math.max(0, Math.min(255, Number(value) || 0)); return ('0' + value.toString(16)).slice(-2); } return '#' + part(red) + part(green) + part(blue); }
  function tvModeTarget(explicitTarget) { var scope = getSetting('jarvisTvTarget', 'auto'); if (explicitTarget) return explicitTarget; if (scope === 'tv') return 'tv lights'; if (scope === 'both') return null; if (targetSelect && targetSelect.value === 'tv lights') return 'tv lights'; return null; }
  function tvSettings() { var speed = getSetting('jarvisTvSpeed', 'fast'), profile = getSetting('jarvisTvProfile', 'cinema'), table = { instant: { delay: 180, smoothing: 0.34, threshold: 13 }, fast: { delay: 260, smoothing: 0.58, threshold: 18 }, smooth: { delay: 420, smoothing: 0.74, threshold: 24 } }; return { profile: profile, delay: (table[speed] || table.fast).delay, smoothing: (table[speed] || table.fast).smoothing, threshold: (table[speed] || table.fast).threshold, intensity: profile === 'vivid' ? 1.24 : profile === 'soft' ? 0.78 : profile === 'dark' ? 0.58 : 0.96 }; }
  function enhanceMovieColor(red, green, blue) { var settings = tvSettings(), max = Math.max(red, green, blue), min = Math.min(red, green, blue), gray = (red + green + blue) / 3, sat = settings.profile === 'vivid' ? 1.45 : settings.profile === 'soft' ? 1.08 : settings.profile === 'dark' ? 1.22 : 1.25, value = settings.profile === 'dark' ? 0.72 : settings.profile === 'soft' ? 0.92 : 1.03, floor = settings.profile === 'dark' ? 8 : settings.profile === 'soft' ? 18 : 22; if (max - min < 14) sat = Math.min(sat, 1.08); red = gray + (red - gray) * sat; green = gray + (green - gray) * sat; blue = gray + (blue - gray) * sat; return { red: Math.max(floor, Math.min(220, Math.round(red * value * settings.intensity))), green: Math.max(floor, Math.min(220, Math.round(green * value * settings.intensity))), blue: Math.max(floor, Math.min(220, Math.round(blue * value * settings.intensity))) }; }
  function shouldSendCameraColor(color) { var settings = tvSettings(), last, delta; if (!cameraLastColor) return true; last = cameraLastColor.split(','); delta = Math.abs(color.red - Number(last[0])) + Math.abs(color.green - Number(last[1])) + Math.abs(color.blue - Number(last[2])); return delta >= settings.threshold; }
  function renderTargets(targets) { var current, i, item, option; if (!targetSelect || !targets) return; current = targetSelect.value; targetSelect.innerHTML = ''; for (i = 0; i < targets.length; i += 1) { item = targets[i]; option = document.createElement('option'); option.value = item.value; option.text = item.label; targetSelect.appendChild(option); } targetSelect.value = current; }
  function deviceCard(device, actionText, action) { var card = document.createElement('div'), summary = document.createElement('div'), name = document.createElement('strong'), address = document.createElement('span'), label = document.createElement('input'), button = document.createElement('button'), statusText = '', reachable = device.reachable; card.className = 'device-card' + (device.likely_lotus ? ' likely' : '') + (reachable === true ? ' reachable' : reachable === false ? ' unreachable' : ''); name.textContent = device.label || device.name || 'Unnamed device'; if (device.paired) statusText = ' · paired'; if (reachable === true) statusText += ' · connected'; if (reachable === false) statusText += ' · connection issue'; if (device.error) statusText += ' · ' + device.error; address.textContent = (device.address || '') + statusText; summary.appendChild(name); summary.appendChild(address); label.value = device.label || device.name || ''; label.placeholder = 'Light name'; button.type = 'button'; button.textContent = actionText; button.onclick = function () { action(label.value); }; card.appendChild(summary); card.appendChild(button); card.appendChild(label); return card; }
  function renderPairedLamps(data) { var i, item; if (!pairedLamps || !data) return; pairedLamps.innerHTML = ''; renderTargets(data.targets); if (!data.controllers || !data.controllers.length) { pairedLamps.textContent = 'No lamps paired yet.'; return; } for (i = 0; i < data.controllers.length; i += 1) { item = data.controllers[i]; pairedLamps.appendChild(deviceCard(item, 'Save', function (label) { return function (value) { pairLamp({ controller: label.controller, name: label.name, address: label.address, label: value }); }; }(item))); } }
  function refreshLampPairing() { if (!token) return; apiGet('/api/lotus/pairing/status', renderPairedLamps, function (error) { if (pairedLamps) pairedLamps.textContent = error.message || 'Could not load paired lamps.'; }); }
  function pairLamp(device) { showOutcome('Pairing ' + (device.label || device.name || 'lamp') + '...'); apiPost('/api/lotus/pairing/pair', device, function (data) { showOutcome(data.reachable === false ? 'Saved ' + (data.label || data.name || 'lamp') + ', but I could not connect yet.' : 'Paired ' + (data.label || data.name || 'lamp') + '.'); refreshLampPairing(); loadToolCatalog(); }, function (error) { showOutcome(error.message || 'Pairing failed.', true); }); }
  function reconnectLamps() { if (!pairedLamps) return; pairedLamps.textContent = 'Reconnecting saved Lotus lamps...'; apiPost('/api/lotus/pairing/reconnect', {}, function (data) { renderPairedLamps(data); showOutcome(data.message || 'Lamp reconnect complete.', data.ok === false); loadToolCatalog(); }, function (error) { showOutcome(error.message || 'Lamp reconnect failed.', true); refreshLampPairing(); }); }
  function scanForLamps() { if (!lampScanResults) return; lampScanResults.textContent = 'Scanning from the Jarvis PC...'; apiPost('/api/lotus/pairing/scan', {}, function (data) { var i, device; lampScanResults.innerHTML = ''; if (!data.devices || !data.devices.length) { lampScanResults.textContent = 'No Bluetooth devices found.'; return; } for (i = 0; i < data.devices.length; i += 1) { device = data.devices[i]; lampScanResults.appendChild(deviceCard(device, device.paired ? 'Repair' : 'Pair', function (picked) { return function (label) { if (picked.paired) { reconnectLamps(); return; } pairLamp({ controller: picked.controller || null, name: picked.name || 'Lotus lamp', address: picked.address, label: label }); }; }(device))); } }, function (error) { lampScanResults.textContent = error.message || 'Bluetooth scan failed.'; setState('error', { message: lampScanResults.textContent }); }); }
  function renderTools(data) {
    var i, item, button, option, color;
    if (!data || !data.lights) return;
    renderTargets(data.lights.targets);
    if (colorSwatches) {
      colorSwatches.innerHTML = '';
      for (i = 0; i < data.lights.colors.length; i += 1) {
        color = data.lights.colors[i];
        button = document.createElement('button');
        button.type = 'button';
        button.title = color.name;
        button.setAttribute('aria-label', color.name);
        button.style.background = rgbToHex(color.red, color.green, color.blue);
        button.onclick = (function (picked) { return function () { colorInput.value = rgbToHex(picked.red, picked.green, picked.blue); callTool('lotus_set_color', targetArgs({ color: picked.name })); }; }(color));
        colorSwatches.appendChild(button);
      }
    }
    if (effectGrid) {
      effectGrid.innerHTML = '';
      for (i = 0; i < data.lights.effects.length; i += 1) {
        item = data.lights.effects[i];
        button = document.createElement('button');
        button.type = 'button';
        button.innerHTML = '<strong>' + item.label + '</strong><span>' + item.description + '</span>';
        button.onclick = (function (effect) { return function () { callTool('lotus_set_effect', targetArgs({ effect: effect.name })); }; }(item));
        effectGrid.appendChild(button);
      }
    }
    if (toolName) {
      toolName.innerHTML = '';
      for (i = 0; i < data.tools.length; i += 1) {
        item = data.tools[i];
        option = document.createElement('option');
        option.value = item.name;
        option.text = item.name;
        toolName.appendChild(option);
      }
    }
  }
  function loadToolCatalog() { if (!token) return; apiGet('/api/tools', renderTools, function (error) { showOutcome(error.message || 'Could not load tools.', true); }); }
  function serverMicMessage(data) { return data && data.awaiting_command ? 'Yes?' : 'Server microphone ready'; }
  function showServerMicStatus(data) { if (data && data.awaiting_command) setState('listening', { message: 'Yes?' }); else setState('idle', { message: serverMicMessage(data) }); }
  function syncServerMicStatus() { if (getSetting('jarvisMicSource', 'server') !== 'server' || !token) return; apiGet('/api/server/mic/status', showServerMicStatus, function () {}); }
  function startServerMic() { apiPost('/api/server/mic/start', {}, showServerMicStatus, function (error) { setState('error', { message: error.message || 'Server microphone issue.' }); }); }
  function stopServerMic() { apiPost('/api/server/mic/stop', {}, function () {}, function () {}); }
  function checkServerCamera() { apiGet('/api/server/camera/status', function (data) { if (data.available) message.textContent = 'Server camera ready ' + data.color; else setState('error', { message: data.error || 'Server camera is not available.' }); }, function (error) { setState('error', { message: error.message || 'Server camera issue.' }); }); }
  function requestReply(text) { apiPost('/api/chat', { text: text, session_id: sessionId }, function (data) { processing = false; sessionId = data.session_id; message.textContent = data.reply; say(data.reply); }, function (error) { processing = false; setState('error', { message: error.message || 'Connection issue.' }); setTimeout(function () { setState('idle'); startListening(); }, 2800); }); }
  function submit(text) { if (!text || !token || processing) return; clientLog('submit', { text_length: text.length, wake_only: wakeOnly }); stopSpeaking(); clearTimeout(commandTimer); clearListeningTimeout(); wakeOnly = false; processing = true; if (recognition) { try { recognition.abort(); } catch (ignore) {} } setState('thinking', { message: 'Thinking' }); playThinkingSound(); requestReply(text); }
  function submitCommand() { var text = commandText.replace(/^\s+|\s+$/g, ''); if (!wakeOnly || !text) return; clientLog('speech_submit_command', { text: text }); submit(text); }
  function resetCommandTimer(delay) { clearTimeout(commandTimer); armListeningTimeout(); commandTimer = setTimeout(submitCommand, delay || 650); }
  function handleSpeech(text) { var cleaned = text.replace(/^\s+|\s+$/g, ''); var wake = /\b(?:hey\s+)?(?:jarvis|jervis|jar vise|jarvus)\b[,.!\s]*/i; clientLog('speech_final', { text: cleaned, wake: wake.test(cleaned) }); if (!wake.test(cleaned)) return; playWakeChime(); var command = cleaned.replace(wake, '').replace(/^\s+|\s+$/g, ''); if (command) submit(command); else { wakeOnly = true; commandText = ''; setState('listening', { message: 'Yes?' }); say('Yes?', function () { setState('listening', { message: 'Listening...' }); armListeningTimeout(); startListening(); }, 'listening'); } }
  function requestMicrophone() { unlockAudio(); if (speaking) { stopSpeaking(); setState('idle', { message: 'Interrupted.' }); } if (getSetting('jarvisMicSource', 'server') === 'server') { setState('thinking', { message: 'Starting server microphone...' }); startServerMic(); return; } if (!window.isSecureContext) { setState('error', { message: 'Open Jarvis with https. Tap ? for certificate help.' }); return; } listenWanted = true; wakeOnly = false; clearListeningTimeout(); startListening(); setState('idle', { message: 'Listening for wake phrase' }); }
  function postMusicColor(red, green, blue, energy) { apiPost('/api/lotus/music-color', { red: red, green: green, blue: blue, energy: energy }, function () {}, function () {}); }
  function musicColorFromAudio(bytes) { var low = 0, mid = 0, high = 0, i, energy, red, green, blue; for (i = 2; i < 12 && i < bytes.length; i += 1) low += bytes[i]; for (i = 12; i < 44 && i < bytes.length; i += 1) mid += bytes[i]; for (i = 44; i < 96 && i < bytes.length; i += 1) high += bytes[i]; low = low / 10; mid = mid / 32; high = high / 52; energy = Math.min(1, (low * 0.55 + mid * 0.35 + high * 0.25) / 150); red = Math.round(18 + low * 0.72 + energy * 70); green = Math.round(12 + mid * 0.82 + energy * 80); blue = Math.round(32 + high * 0.95 + energy * 100); return { red: Math.min(210, red), green: Math.min(210, green), blue: Math.min(230, blue), energy: energy }; }
  function tickMusicSync() { var bytes, color, key; if (!musicSync || !musicAnalyser) return; bytes = new Uint8Array(musicAnalyser.frequencyBinCount); musicAnalyser.getByteFrequencyData(bytes); color = musicColorFromAudio(bytes); key = color.red + ',' + color.green + ',' + color.blue; if (color.energy > 0.035 && key !== musicLastColor) { musicLastColor = key; postMusicColor(color.red, color.green, color.blue, color.energy); } musicTimer = setTimeout(tickMusicSync, 260); }
  function stopMusicSync() { musicSync = false; if (musicTimer) clearTimeout(musicTimer); musicTimer = null; if (musicStream) { musicStream.getTracks().forEach(function (track) { track.stop(); }); } musicStream = null; musicSource = null; musicAnalyser = null; if (musicAudio) { try { musicAudio.close(); } catch (ignore) {} } musicAudio = null; message.textContent = 'Music sync stopped'; }
  function startMusicSync() { var AudioContext = window.AudioContext || window.webkitAudioContext, getAudio; if (!window.isSecureContext) { setState('error', { message: 'Open Jarvis with https. Tap ? for certificate help.' }); return; } if (!AudioContext || !navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) { setState('error', { message: 'This browser cannot share microphone audio.' }); return; } stopMusicSync(); stopCameraSync(); musicSync = true; getAudio = navigator.mediaDevices.getUserMedia({ audio: true }); getAudio.then(function (stream) { musicStream = stream; musicAudio = new AudioContext(); musicSource = musicAudio.createMediaStreamSource(stream); musicAnalyser = musicAudio.createAnalyser(); musicAnalyser.fftSize = 256; musicAnalyser.smoothingTimeConstant = 0.72; musicSource.connect(musicAnalyser); message.textContent = 'Music sync listening'; tickMusicSync(); }).catch(function () { musicSync = false; setState('error', { message: 'Allow microphone access for music sync. Tap ? if it is blocked.' }); }); }
  function postCameraColor(red, green, blue) { apiPost('/api/lotus/music-color', { red: red, green: green, blue: blue, energy: 0.5, target: cameraTarget }, function () {}, function () {}); }
  function stopCameraSync() { cameraSync = false; if (cameraTimer) clearTimeout(cameraTimer); cameraTimer = null; if (cameraStream) { cameraStream.getTracks().forEach(function (track) { track.stop(); }); } cameraStream = null; cameraVideo = null; cameraCanvas = null; cameraContext = null; cameraTarget = null; message.textContent = 'Camera color match stopped'; }
  function tickServerCamera() { var settings; if (!cameraSync) return; settings = tvSettings(); apiPost('/api/lotus/camera-color', { target: cameraTarget, profile: settings.profile, smoothing: settings.smoothing, intensity: settings.intensity, threshold: settings.threshold }, function (data) { cameraFailures = 0; if (data && data.color) message.textContent = 'TV mode ' + data.color; cameraTimer = setTimeout(tickServerCamera, settings.delay); }, function (error) { cameraFailures += 1; setState('error', { message: error.message || 'Server camera connection issue.' }); if (cameraFailures >= 3) { stopCameraSync(); message.textContent = 'Server camera stopped after repeated connection issues.'; return; } cameraTimer = setTimeout(tickServerCamera, 1200); }); }
  function tickLocalCamera() { var width, height, data, totalRed = 0, totalGreen = 0, totalBlue = 0, count = 0, i, key, red, green, blue, x, y, pixel, color, settings; if (!cameraSync || !cameraVideo || !cameraContext) return; settings = tvSettings(); width = 48; height = 27; cameraContext.drawImage(cameraVideo, 0, 0, width, height); data = cameraContext.getImageData(0, 0, width, height).data; for (y = 3; y < height - 3; y += 1) { for (x = 5; x < width - 5; x += 1) { pixel = (y * width + x) * 4; totalRed += data[pixel]; totalGreen += data[pixel + 1]; totalBlue += data[pixel + 2]; count += 1; } } red = Math.round(totalRed / count); green = Math.round(totalGreen / count); blue = Math.round(totalBlue / count); color = enhanceMovieColor(red, green, blue); key = color.red + ',' + color.green + ',' + color.blue; if (shouldSendCameraColor(color)) { cameraLastColor = key; postCameraColor(color.red, color.green, color.blue); } cameraTimer = setTimeout(tickLocalCamera, settings.delay); }
  function startLocalCameraSync(target) { if (!window.isSecureContext) { setState('error', { message: 'Open Jarvis with https or use server camera mode.' }); return; } if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) { setState('error', { message: 'This browser cannot share camera. Use server camera mode.' }); return; } stopCameraSync(); cameraTarget = target || null; cameraSync = true; navigator.mediaDevices.getUserMedia({ video: true, audio: false }).then(function (stream) { cameraStream = stream; cameraVideo = document.createElement('video'); cameraVideo.autoplay = true; cameraVideo.muted = true; cameraVideo.srcObject = stream; cameraCanvas = document.createElement('canvas'); cameraCanvas.width = 48; cameraCanvas.height = 27; cameraContext = cameraCanvas.getContext('2d'); message.textContent = 'Camera color match listening'; setTimeout(tickLocalCamera, 600); }).catch(function () { cameraSync = false; setState('error', { message: 'Camera blocked. Use server camera mode.' }); }); }
  function startCameraSync(source, target) { source = source === 'settings' || !source ? getSetting('jarvisCameraSource', 'server') : source; target = tvModeTarget(target); if (source === 'local') startLocalCameraSync(target); else { stopCameraSync(); cameraTarget = target || null; cameraFailures = 0; cameraLastColor = ''; cameraSync = true; message.textContent = cameraTarget ? 'TV mode started for ' + cameraTarget : 'TV mode started for both lights'; tickServerCamera(); } }
  function startTvMode() { var target = tvModeTarget(null), settings = tvSettings(), source = getSetting('jarvisCameraSource', 'server'), args = { enabled: true, source: source }; if (target) args.target = target; if (source === 'local') { callTool('lotus_camera_sync', args); return; } if (sphere) sphere.startAction('Starting TV mode', null); apiPost('/api/lotus/tv-mode/start', { enabled: true, target: target, profile: settings.profile, smoothing: settings.smoothing, intensity: settings.intensity, threshold: settings.threshold, delay_ms: settings.delay }, function () { stopCameraSync(); cameraSync = true; cameraTarget = target || null; message.textContent = cameraTarget ? 'TV mode running on the Jarvis PC for ' + cameraTarget : 'TV mode running on the Jarvis PC'; showOutcome('TV mode started on the Jarvis PC.'); if (sphere) sphere.setState('idle', { message: 'TV mode running on the Jarvis PC' }); }, function (error) { showOutcome(error.message || 'TV mode failed to start.', true); if (sphere) sphere.failAction(error.message || 'TV mode failed to start.'); }); }
  function stopTvMode() { apiPost('/api/lotus/tv-mode/stop', {}, function () { stopCameraSync(); showOutcome('TV mode stopped.'); }, function (error) { stopCameraSync(); showOutcome(error.message || 'TV mode stopped locally, but the server did not confirm.', true); }); }
  if (tabs) tabs.onclick = function (event) { var button = event.target, buttons, panels, i; if (!button || !button.getAttribute('data-panel')) return; buttons = tabs.getElementsByTagName('button'); panels = controls.getElementsByClassName('control-panel'); for (i = 0; i < buttons.length; i += 1) buttons[i].className = buttons[i] === button ? 'active' : ''; for (i = 0; i < panels.length; i += 1) panels[i].className = panels[i].id === button.getAttribute('data-panel') ? 'control-panel active' : 'control-panel'; };
  if (document.getElementById('lights-on')) document.getElementById('lights-on').onclick = function () { callTool('lotus_turn_on', targetArgs({})); };
  if (document.getElementById('lights-off')) document.getElementById('lights-off').onclick = function () { callTool('lotus_turn_off', targetArgs({})); };
  if (colorInput) colorInput.onchange = function () { var rgb = hexToRgb(colorInput.value); callTool('lotus_set_rgb', targetArgs(rgb)); };
  if (brightness) brightness.oninput = function () { if (brightnessValue) brightnessValue.textContent = brightness.value + '%'; };
  if (brightness) brightness.onchange = function () { var rgb = hexToRgb(colorInput && colorInput.value ? colorInput.value : '#ffffff'); callTool('lotus_set_brightness', targetArgs({ brightness: Number(brightness.value), red: rgb.red, green: rgb.green, blue: rgb.blue })); };
  if (document.getElementById('stop-effect')) document.getElementById('stop-effect').onclick = function () { callTool('lotus_stop_effect', targetArgs({})); stopMusicSync(); stopCameraSync(); };
  if (document.getElementById('music-sync')) document.getElementById('music-sync').onclick = function () { callTool('lotus_music_sync', { enabled: !musicSync }); };
  if (document.getElementById('camera-sync')) document.getElementById('camera-sync').onclick = startTvMode;
  if (document.getElementById('camera-sync-off')) document.getElementById('camera-sync-off').onclick = stopTvMode;
  if (document.getElementById('run-tool')) document.getElementById('run-tool').onclick = function () { var args = {}; try { args = JSON.parse(toolArguments.value || '{}'); } catch (error) { showOutcome('Tool arguments must be valid JSON.', true); return; } callTool(toolName.value, args); };
  Array.prototype.forEach.call(document.querySelectorAll('[data-command]'), function (button) { button.onclick = function () { submit(button.getAttribute('data-command')); }; });
  form.onsubmit = function (event) { event.preventDefault(); var text = input.value; input.value = ''; submit(text); };
  var Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  markSurfaceCompat();
  if (micSource) micSource.value = getSetting('jarvisMicSource', Recognition ? 'local' : 'server');
  if (cameraSource) cameraSource.value = getSetting('jarvisCameraSource', 'server');
  if (tvProfile) tvProfile.value = getSetting('jarvisTvProfile', 'cinema');
  if (tvTarget) tvTarget.value = getSetting('jarvisTvTarget', 'auto');
  if (tvSpeed) tvSpeed.value = getSetting('jarvisTvSpeed', 'fast');
  document.addEventListener('click', unlockAudio, true);
  document.addEventListener('touchstart', unlockAudio, true);
  document.addEventListener('keydown', unlockAudio, true);
  if (settingsButton) settingsButton.onclick = function () { settingsPanel.hidden = false; refreshLampPairing(); };
  if (settingsClose) settingsClose.onclick = function () { settingsPanel.hidden = true; };
  if (repairLamps) repairLamps.onclick = reconnectLamps;
  if (scanLamps) scanLamps.onclick = scanForLamps;
  if (micSource) micSource.onchange = function () { saveSetting('jarvisMicSource', micSource.value); if (micSource.value === 'server') startServerMic(); else { stopServerMic(); window.location.reload(); } };
  if (cameraSource) cameraSource.onchange = function () { saveSetting('jarvisCameraSource', cameraSource.value); if (cameraSource.value === 'server') checkServerCamera(); if (cameraSync) startCameraSync('settings'); };
  if (tvProfile) tvProfile.onchange = function () { saveSetting('jarvisTvProfile', tvProfile.value); cameraLastColor = ''; };
  if (tvTarget) tvTarget.onchange = function () { saveSetting('jarvisTvTarget', tvTarget.value); if (cameraSync) startCameraSync('settings'); };
  if (tvSpeed) tvSpeed.onchange = function () { saveSetting('jarvisTvSpeed', tvSpeed.value); cameraLastColor = ''; };
  if (getSetting('jarvisMicSource', Recognition ? 'local' : 'server') === 'server') {
    message.textContent = isLocalClient() ? 'Server mic mode selected. Listening on the Jarvis PC.' : 'Server mic mode selected. Tap Mic to start the Jarvis PC microphone.';
    if (token && isLocalClient() && getSetting('jarvisServerMicAutoStart', 'local') === 'local') startServerMic();
  } else if (!window.isSecureContext && location.hostname !== 'localhost' && location.hostname !== '127.0.0.1') {
    message.textContent = 'Open Jarvis with https. Tap ? for certificate help.';
  } else if (Recognition) {
    recognition = new Recognition(); recognition.continuous = true; recognition.interimResults = false; recognition.lang = 'en-US';
    recognition.onstart = function () { if (!speaking) { if (wakeOnly) setState('listening', { message: 'Listening…' }); else setState('idle'); } };
    recognition.onresult = function (event) { var text = '', finalResult; for (var i = event.resultIndex; i < event.results.length; i += 1) text += event.results[i][0].transcript; finalResult = event.results[event.results.length - 1].isFinal; if (wakeOnly) { commandText = text; clientLog('speech_followup_result', { text: text, final: finalResult }); resetCommandTimer(finalResult ? 150 : 900); if (finalResult) submitCommand(); } else if (finalResult) handleSpeech(text); };
    recognition.onspeechend = function () { if (wakeOnly) resetCommandTimer(350); };
    recognition.onsoundend = function () { if (wakeOnly && commandText) resetCommandTimer(450); };
    recognition.onaudioend = function () { if (wakeOnly && commandText) resetCommandTimer(550); };
    recognition.onerror = function (event) { clientLog('speech_error', { error: event.error }); if (event.error === 'not-allowed' || event.error === 'service-not-allowed') { listenWanted = false; setState('error', { message: 'Microphone blocked. Tap ? for certificate help.' }); } };
    recognition.onend = function () { if (listenWanted && !speaking && !processing) restartTimer = setTimeout(startListening, 250); };
    listenWanted = true;
  } else { message.textContent = 'This browser does not expose speech recognition. Tap ? for options.'; }
  function handleAssistantState(eventData) { var data = eventData.data || {}; if (eventData.state !== 'listening') clearListeningTimeout(); if (data.chime) playWakeChime(); if (eventData.state === 'speaking' && data.text) { if (processing) { setState(eventData.state, data); return; } message.textContent = data.text; say(data.text); return; } if (data.say) { setState(eventData.state, data); say(data.say, function () { setState(data.after_say_state || eventData.state, { message: data.after_say_message || data.message }); if ((data.after_say_state || eventData.state) === 'listening') armListeningTimeout(); }, data.say_state || eventData.state); return; } setState(eventData.state, data); if (eventData.state === 'listening') armListeningTimeout(); }
  function connect() { var protocol = location.protocol === 'https:' ? 'wss:' : 'ws:'; var socket = new WebSocket(protocol + '//' + location.host + '/ws', 'jarvis.' + token); socket.onopen = function () { syncServerMicStatus(); if (sphere) sphere.setState('idle', { message: 'Connected' }); }; socket.onmessage = function (event) { var eventData = JSON.parse(event.data), source, color, streaming; if (eventData.type === 'assistant_state') handleAssistantState(eventData); if (eventData.type === 'visual_state' && eventData.state === 'lights' && eventData.data.color) { color = sphere && sphere.parseColor(eventData.data.color); streaming = eventData.data.source === 'server_tv_mode' || eventData.data.source === 'server_camera' || eventData.data.energy !== undefined || eventData.data.effect || eventData.data.effect_sequence; if (sphere && color) { if (streaming) sphere.setColor(color); else sphere.completeAction(color); } document.getElementById('ambient').style.background = eventData.data.color; face.style.borderColor = eventData.data.color; if (colorInput) colorInput.value = eventData.data.color; if (!musicSync && !cameraSync && !streaming) message.textContent = 'Lights updated'; } if (eventData.type === 'music_sync') { if (eventData.state === 'on') startMusicSync(); else { stopMusicSync(); stopCameraSync(); } } if (eventData.type === 'camera_sync') { if (eventData.state === 'on') { source = eventData.data && eventData.data.source; if (source === 'local') startCameraSync(source, eventData.data && eventData.data.target); else { stopCameraSync(); cameraSync = true; cameraTarget = eventData.data && eventData.data.target || null; message.textContent = 'TV mode running on the Jarvis PC'; } } else stopCameraSync(); } }; socket.onclose = function (event) { if (sphere) sphere.setOffline(); if (event.code === 1008) { sessionStorage.removeItem('jarvisToken'); window.location.reload(); return; } if (token) setTimeout(connect, 3000); }; socket.onerror = function () { if (sphere) sphere.setOffline(); }; }
  function setMode(mode) { shell.setAttribute('data-mode', mode); sessionStorage.setItem('jarvisDisplayMode', mode); modeButton.textContent = mode === 'face' ? '◐' : mode === 'black' ? '●' : mode === 'hidden' ? '○' : ''; modeButton.setAttribute('aria-label', 'Display mode: ' + mode + '. Change display mode.'); }
  if (modeButton) { setMode(sessionStorage.getItem('jarvisDisplayMode') || 'face'); modeButton.onclick = function () { var current = shell.getAttribute('data-mode'); setMode(current === 'face' ? 'black' : current === 'black' ? 'hidden' : current === 'hidden' ? 'blackout' : 'face'); }; }
  document.addEventListener('keydown', function (event) { if (event.key === 'Escape' && shell.getAttribute('data-mode') === 'blackout') setMode('face'); });
  document.addEventListener('dblclick', function () { if (shell.getAttribute('data-mode') === 'blackout') setMode('face'); });
  setInterface(getSetting('jarvisInterface', 'default'), false);
  if (interfaceSelect) interfaceSelect.onchange = function () { setInterface(interfaceSelect.value, true); };
  setControlsVisible(false);
  if (controlsToggle) controlsToggle.onclick = toggleControls;
  if (document.getElementById('sphere-interface')) document.getElementById('sphere-interface').onclick = function () { if (shell.getAttribute('data-mode') !== 'blackout') toggleControls(); };
  if (document.getElementById('talk')) document.getElementById('talk').onclick = requestMicrophone;
  if (token) { if (pairing) pairing.hidden = true; loadToolCatalog(); refreshLampPairing(); connect(); startListening(); } else { if (pairing) pairing.hidden = false; message.textContent = 'Pair this browser to begin.'; }
  setState('idle');
}());
